### ISSUE TITLE
HiveFlow and HiveRiffle should provide asynchronous start method

### ISSUE THREAD

**Issue by stephanh** [Cascading/cascading-hive#10]
In order to be consistent with the general Flow interface, HiveFlow and/or HiveRiffle should implement the start method which asynchronously starts the job.

Without this the `Execution.run` method in Scalding won't work since it doesn't call the complete method but instead uses the start method and a FlowListener to listen for the complete event.

**Comment by cwensel** [comment]
Good catch, unsure what that wasn't implemented. Will put it on the next sprint planning list.

So it sounds like you are using Scalding calls to chain those with HiveFlows?

**Comment by stephanh** [comment]
I'm working on an implementation for this atm and will do a PR. However, it will be good to have someone from Concurrent fix it up or replace it since I'll probably miss somethings.

Right now we are wrapping Hive flow into a Scalding job and then use Scalding Cascading job to create a cascade from a List of jobs. (https://github.com/CommBank/maestro/blob/master/maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerCascade.scala#L30-L76).

We are now looking at the Execution monad in Scalding 0.12 since that approach will suit the ETL workflow more. However, that uses https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/java/com/twitter/scalding/cascading_interop/FlowListenerPromise.java to run non scalding flows, which expects an asynchronous start method and the Flow to trigger onComplete and onThorwable events.

**Comment by fs111** [comment]
I have just pushed out async start support on wip-1.0, which will eventually turn into the 1.0.1 release. Next to that I also opened the wip-1.1 branch, which also contains that support, but will be the one, where we develop new features.  Please give them a try and let me know, if something breaks for you.

**Comment by fs111** [comment]
fixed for a long time. Closing.
