### ISSUE TITLE
gradle install failing:Artifact 'commons-logging:commons-logging:1.1.3@jar' not found

### ISSUE THREAD

**Issue by jijomathew35** [Cascading/cascading-hive#12]
gradle install is failing due to the error Artifact 'commons-logging:commons-logging:1.1.3@jar' not found

I tried it on the root as well as the inner folders failing in both the cases.
In cascading-hive folder, when I tried gradle install, it fails with the exception:-
Build file 'C:\Users\dk\cascading hive\cascading-hive-1.0\build.gradle' line: 37
- What went wrong:
  A problem occurred evaluating root project 'cascading-hive'.
  > Could not resolve all dependencies for configuration 'classpath'.
  > Could not download artifact 'commons-logging:commons-logging:1.1.3@jar'
    > Artifact 'commons-logging:commons-logging:1.1.3@jar' not found.

**Comment by fs111** [comment]
This looks like a broken $HOME/.m2 repository. Could you delete that and try again? Also it should not be necessary to install cascading-hive by hand, since we host it on our maven repository: 

http://conjars.org/cascading/cascading-hive/versions/1.0.0

**Comment by jijomathew35** [comment]
Deleting the repository did not help.
But I could get a maven build working, which was enough.
Thanks for the help.
