### ISSUE TITLE
use cascading hive on tez very slow

### ISSUE THREAD

**Issue by r7raul1984** [Cascading/cascading-hive#15]
I append hive-site.xml  as follows:

```
<property>
    <name>hive.execution.engine</name>
    <value>tez</value>
</property>
<property>
    <name>mapreduce.framework.name</name>
    <value>yarn-tez</value>
</property>
<property>
    <name>tez.lib.uris</name>
    <value>hdfs:///apps/tez-0.5.3/tez-0.5.3.tar.gz</value>
</property>
```

Then I run yarn jar build/libs/cascading-hive-demo-1.0.jar cascading.hive.HiveDemo 

The Job run successful , but very slow .Slower than hive on mr.
Some logs as follows:
15/02/11 23:07:06 INFO HiveMetaStore.audit: ugi=hdfs    ip=unknown-ip-addr  cmd=Metastore shutdown complete.  
15/02/11 23:07:06 WARN conf.HiveConf: HiveConf of name hive.optimize.mapjoin.mapreduce does not exist
15/02/11 23:07:06 WARN conf.HiveConf: HiveConf of name hive.semantic.analyzer.factory.impl does not exist
15/02/11 23:07:06 WARN conf.HiveConf: HiveConf of name hive.auto.convert.sortmerge.join.noconditionaltask does not exist
15/02/11 23:07:06 INFO session.SessionState: Created local directory: /tmp/61d91f93-0f22-4ebb-8fae-0dff14b8bbd7_resources
15/02/11 23:07:06 INFO session.SessionState: Created HDFS directory: /tmp/hive/hdfs/61d91f93-0f22-4ebb-8fae-0dff14b8bbd7
15/02/11 23:07:06 INFO session.SessionState: Created local directory: /tmp/hdfs/61d91f93-0f22-4ebb-8fae-0dff14b8bbd7
15/02/11 23:07:06 INFO session.SessionState: Created HDFS directory: /tmp/hive/hdfs/61d91f93-0f22-4ebb-8fae-0dff14b8bbd7/_tmp_space.db
15/02/11 23:07:06 INFO tez.TezSessionState: User of session id 61d91f93-0f22-4ebb-8fae-0dff14b8bbd7 is hdfs
15/02/11 23:07:06 INFO tez.DagUtils: Jar dir is null/directory doesn't exist. Choosing HIVE_INSTALL_DIR - hdfs:/user/hdfs/.hiveJars
15/02/11 23:07:06 INFO tez.DagUtils: Resource modification time: 1423663740552
15/02/11 23:07:06 INFO client.TezClient: Tez Client Version: [ component=tez-api, version=0.5.3, revision=${buildNumber}, SCM-URL=scm:git:https://git-wip-us.apache.org/repos/asf/tez.git, buildTime=20150112-2131 ]
15/02/11 23:07:06 INFO tez.TezSessionState: Opening new Tez Session (id: 61d91f93-0f22-4ebb-8fae-0dff14b8bbd7, scratch dir: hdfs://localhost:8020/tmp/hive/hdfs/_tez_session_dir/61d91f93-0f22-4ebb-8fae-0dff14b8bbd7)
15/02/11 23:07:06 INFO client.RMProxy: Connecting to ResourceManager at localhost/127.0.0.1:8032
15/02/11 23:07:06 INFO client.TezClient: Session mode. Starting session.
15/02/11 23:07:06 INFO client.TezClientUtils: Using tez.lib.uris value from configuration: hdfs:///apps/tez-0.5.3/tez-0.5.3.tar.gz
15/02/11 23:07:06 INFO client.TezClient: Tez system stage directory hdfs://localhost:8020/tmp/hive/hdfs/_tez_session_dir/61d91f93-0f22-4ebb-8fae-0dff14b8bbd7/.tez/application_1422003283699_0139 doesn't exist and is created
15/02/11 23:07:06 INFO impl.YarnClientImpl: Submitted application application_1422003283699_0139
15/02/11 23:07:06 INFO client.TezClient: The url to track the Tez Session: http://localhost:8088/proxy/application_1422003283699_0139/

The job block here for a long time.

**Comment by fs111** [comment]
Can you confirm that running the same queries in hive w/o using cascading-hive is faster? If that is the case, we have a bug, otherwise you have to ask the Hive community for help.

In cascading-hive we treat Hive like a black-box, which means that we don't know how things are being executed, we just wait for Hive to do it's processing before scheduling the next Flow.

**Comment by r7raul1984** [comment]
I  run the query in beeline is faster.
The log as follows :

+---------------+-----------------+--+ 
3 rows selected (0.124 seconds) 
0: jdbc:hive2://192.168.117.117:14000> set hive.execution.engine=tez; 
No rows affected (0.005 seconds) 
0: jdbc:hive2://192.168.117.117:14000> select \* from keyvalue; 
+---------------+-----------------+--+ 
| keyvalue.key | keyvalue.value | 
+---------------+-----------------+--+ 
| Hello | hive! | 
| Multiple | queries | 
| are | supported | 
+---------------+-----------------+--+ 
3 rows selected (0.119 seconds) 
0: jdbc:hive2://192.168.117.117:14000> insert overwrite table keyvalue select 'Hello' as key, 'hive!' as value from dual; 
No rows affected (4.693 seconds) 
0: jdbc:hive2://192.168.117.117:14000> select \* from keyvalue; 
+---------------+-----------------+--+ 
| keyvalue.key | keyvalue.value | 
+---------------+-----------------+--+ 
| Hello | hive! | 
+---------------+-----------------+--+ 
1 row selected (0.122 seconds) 
0: jdbc:hive2://192.168.117.117:14000> insert into table keyvalue select 'Multiple' as key, 'queries' as value from dual; 
No rows affected (4.234 seconds) 
0: jdbc:hive2://192.168.117.117:14000> select \* from keyvalue; 
+---------------+-----------------+--+ 
| keyvalue.key | keyvalue.value | 
+---------------+-----------------+--+ 
| Hello | hive! | 
| Multiple | queries | 
+---------------+-----------------+--+ 
2 rows selected (0.116 seconds) 
0: jdbc:hive2://192.168.117.117:14000> insert into table keyvalue select 'are' as key, 'supported' as value from dual; 
No rows affected (5.038 seconds) 
0: jdbc:hive2://192.168.117.117:14000> select \* from keyvalue; 
+---------------+-----------------+--+ 
| keyvalue.key | keyvalue.value | 
+---------------+-----------------+--+ 
| Hello | hive! | 
| Multiple | queries | 
| are | supported | 
+---------------+-----------------+--+ 
3 rows selected (0.285 seconds) 

I see resourcemanager webUI 
Just one application running :
application_1422003283699_0145hdfsHIVE-f18137fb-6cc0-41e0-8da9-7caded5addb2TEZhdfsThu, 12 Feb 2015 08:55:25 GMTN/ARUNNINGUNDEFINED 
ApplicationMaster

But when I use cascading hive on tez ,Two  Tez application  running :
application_1422003283699_0143hdfs[3B6FF4028F4547D99986E2B07DB78003/D3A0E6FDC5A64989B3D62E2DCDBDB00D] uppercase kv -> kv2 /(1/1) .../hive/warehouse/keyvalue2MAPREDUCEdefaultWed, 11 Feb 2015 17:06:28 GMTWed, 11 Feb 2015 17:12:08 GMTFINISHEDSUCCEEDED 
History
application_1422003283699_0142hdfsHIVE-0289ade0-b9ad-4a49-9fe4-4d7af705d629TEZdefaultWed, 11 Feb 2015 17:01:14 GMTWed, 11 Feb 2015 17:11:54 GMTFINISHEDSUCCEEDED 
History
application_1422003283699_0141hdfsHIVE-36ba7bc8-7ce0-4741-89da-f99a375fc18dTEZdefaultWed, 11 Feb 2015 17:01:08 GMTWed, 11 Feb 2015 17:06:16 GMTFINISHEDSUCCEEDED 

r7raul1984@163.com

From: André Kelpe
Date: 2015-02-11 18:07
To: Cascading/cascading-hive
CC: r7raul1984
Subject: Re: [cascading-hive] use cascading hive on tez very slow (#15)
Can you confirm that running the same queries in hive w/o using cascading-hive is faster? If that is the case, we have a bug, otherwise you have to ask the Hive community for help.
In cascading-hive we treat Hive like a black-box, which means that we don't know how things are being executed, we just wait for Hive to do it's processing before scheduling the next Flow.

**Comment by fs111** [comment]
Is this a real cluster with Tez or local mode?

**Comment by r7raul1984** [comment]
My enviroment  is Hadoop 2.5.0-cdh5.2.0 . Just one host in my cluster.

**Comment by fs111** [comment]
to be honest, I have no idea how this can happen. Do have any more representative workloads where you see that as well? It might be just a setting, which the hive shell does automatically, but we do not. Can you compare the configs used by a job coming from cascading-hive with one coming from the hive shell? That might give an indication whats wrong.

**Comment by fs111** [comment]
Did you investigate this any further? I'd like to understand why this happens.

**Comment by fs111** [comment]
stale problem. Please re-open if the problem still exists.
