### ISSUE TITLE
Need to be able to set performance options for queries

### ISSUE THREAD

**Issue by stephanh** [Cascading/cascading-hive#6]
We want to be able to set specific hive performance options for some of the queries we run. Currently the HiveDriverFactory instantiates a new HiveConf as needed when it creates the driver. 

Would it make sense to have a `createHiveDriver` method that takes a HiveConf as parameter and to modify HiveFlow so that it passes down the HiveConf or is there a better way?

Am I right in thinking there shouldn't be any serialisation issues around HiveConf since the hive flow will be run on the submitter node?

**Comment by fs111** [comment]
What we do in cascading is having a user pass in either a Map<String, Object> or a Properties object with custom configuration settings. These are then being picked up and merged with the JobConf by the FlowConnectors. We should follow a similar approach, where you would pass the properties into the HiveFlow constructor and then merge the values into the HiveConf in the DriverFactory.  We will have to get rid of the caching then, though.

The serialization rules are the same as for JobConf. If you have non-trivial Objects, you can still base64-encode them, if necessary.

**Comment by fs111** [comment]
Closing, since this was done in #7.
